steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/combo-backend',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'gcr.io/$PROJECT_ID/combo-backend'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'combo-backend',
      '--image', 'gcr.io/$PROJECT_ID/combo-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars',
      'FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL},FIREBASE_DATABASE_SECRET=${_FIREBASE_DATABASE_SECRET},JWT_SECRET=${_JWT_SECRET},NODE_ENV=production'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_DATABASE_URL: https://combo-624e1-default-rtdb.firebaseio.com
  _FIREBASE_DATABASE_SECRET: ${FIREBASE_DATABASE_SECRET}
  _JWT_SECRET: ${JWT_SECRET}
