steps:
  - name: "bash"
    id: "Create empty .env file"
    dir: "backend"
    args:
      - "-c"
      - "touch .env"

  - name: "gcr.io/cloud-builders/docker"
    id: "Build"
    dir: "backend"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/combo-repo/${_SERVICE_NAME}:latest"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push"
    args:
      - "push"
      - "us-central1-docker.pkg.dev/${PROJECT_ID}/combo-repo/${_SERVICE_NAME}:latest"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=us-central1-docker.pkg.dev/${PROJECT_ID}/combo-repo/${_SERVICE_NAME}:latest"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--port=8080"
      - "--memory=1Gi"
      - "--cpu=1"
      - "--max-instances=10"
      - "--timeout=300"
      - "--update-env-vars"
      - "NODE_ENV=production,FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}"
      - "--set-secrets=FIREBASE_DATABASE_SECRET=FIREBASE_DATABASE_SECRET:latest,JWT_SECRET=JWT_SECRET:latest"
      - "--quiet"

# Define substitutions
substitutions:
  _SERVICE_NAME: "combo-backend"
  _REGION: "us-central1"
  _FIREBASE_DATABASE_URL: "https://combo-624e1-default-rtdb.firebaseio.com"

options:
  logging: CLOUD_LOGGING_ONLY
