steps:
  # Debug: Show current directory structure
  - name: 'ubuntu'
    id: 'Show directory structure'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory structure:"
        pwd
        ls -la
        echo -e "\nContents of current directory:"
        find . -maxdepth 1 -type d | sort

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/combo-repo/combo-backend',
      '--no-cache',
      '--build-arg', 'NODE_ENV=production',
      '.'
    ]

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/combo-repo/combo-backend'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'combo-backend',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/combo-repo/combo-backend',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '300',
      '--clear-env-vars',
      '--update-env-vars',
      'FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL},FIREBASE_DATABASE_SECRET=${_FIREBASE_DATABASE_SECRET},JWT_SECRET=${_JWT_SECRET},NODE_ENV=production',
      '--quiet'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _FIREBASE_DATABASE_URL: https://combo-624e1-default-rtdb.firebaseio.com
  _FIREBASE_DATABASE_SECRET: ${FIREBASE_DATABASE_SECRET}
  _JWT_SECRET: ${JWT_SECRET}
