steps:
  # Show current directory structure
  - name: 'ubuntu'
    id: 'Show directory structure 1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory structure:"
        pwd
        ls -la
        echo -e "\nContents of current directory:"
        find . -maxdepth 1 -type d | sort

  # Show current directory structure after build
  - name: 'ubuntu'
    id: 'Show directory structure 2'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory structure:"
        pwd
        ls -la
        echo -e "\nContents of current directory:"
        find . -maxdepth 1 -type d | sort

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    dir: '.'  # Run from the root directory
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/combo-624e1/combo-repo/combo-backend',
      '--no-cache',
      '--build-arg', 'NODE_ENV=production',
      '-f', 'backend/Dockerfile',
      'backend'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: [
      'push',
      'us-central1-docker.pkg.dev/combo-624e1/combo-repo/combo-backend'
    ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'combo-backend',
      '--image', 'us-central1-docker.pkg.dev/combo-624e1/combo-repo/combo-backend:latest',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '1Gi',
      '--cpu', '1',
      '--max-instances', '10',
      '--timeout', '300',
      '--set-env-vars', 'NODE_ENV=production',
      '--set-env-vars', 'FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL',
      '--set-env-vars', 'FIREBASE_DATABASE_SECRET=$_FIREBASE_DATABASE_SECRET',
      '--set-env-vars', 'JWT_SECRET=$_JWT_SECRET',
      '--quiet'
    ]
substitutions:
  _FIREBASE_DATABASE_URL: https://combo-624e1-default-rtdb.firebaseio.com
  _FIREBASE_DATABASE_SECRET: ${FIREBASE_DATABASE_SECRET}
  _JWT_SECRET: ${JWT_SECRET}
