# Cloud Build configuration with logging settings
options:
  logging: CLOUD_LOGGING_ONLY

# Define substitutions with default values
substitutions:
  _SERVICE_NAME: combo-backend
  _REGION: us-central1
  _FIREBASE_DATABASE_URL: https://combo-624e1-default-rtdb.firebaseio.com

steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker image'
    dir: 'backend'  # Run from the backend directory
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/combo-624e1/combo-repo/combo-backend:latest',
      '--no-cache',
      '--build-arg', 'NODE_ENV=production',
      '-f', 'Dockerfile',
      '.'
    ]

  # Push the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker image'
    args: [
      'push',
      'us-central1-docker.pkg.dev/combo-624e1/combo-repo/combo-backend:latest'
    ]

  # Deploy to Cloud Run with secrets from Secret Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Set environment variables
        export PROJECT_ID=combo-624e1
        export REGION=${_REGION}
        export SERVICE_NAME=${_SERVICE_NAME}
        export IMAGE=us-central1-docker.pkg.dev/combo-624e1/combo-repo/combo-backend:latest
        export FIREBASE_DATABASE_URL=${_FIREBASE_DATABASE_URL}

        # Enable required services
        gcloud services enable run.googleapis.com \
          cloudbuild.googleapis.com \
          artifactregistry.googleapis.com \
          secretmanager.googleapis.com \
          --quiet || true

        # Deploy the service with environment variables and secrets
        gcloud run deploy $$SERVICE_NAME \
          --image=$$IMAGE \
          --region=$$REGION \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080 \
          --memory=1Gi \
          --cpu=1 \
          --max-instances=10 \
          --timeout=300 \
          --set-env-vars="NODE_ENV=production" \
          --set-env-vars="FIREBASE_DATABASE_URL=$$FIREBASE_DATABASE_URL" \
          --set-secrets="FIREBASE_DATABASE_SECRET=FIREBASE_DATABASE_SECRET:latest" \
          --set-secrets="JWT_SECRET=JWT_SECRET:latest" \
          --quiet

        # Get the service URL
        SERVICE_URL=$(gcloud run services describe $$SERVICE_NAME \
          --region $$REGION \
          --format 'value(status.url)')
        
        echo "Service deployed successfully to: $$SERVICE_URL"
        echo "Health check endpoint: $$SERVICE_URL/health"
        
        # Set the service URL as an output variable
        echo "SERVICE_URL=$$SERVICE_URL" > service-url.txt

# Store the service URL as a build variable
availableSecrets:
  secretManager:
  - versionName: projects/combo-624e1/secrets/FIREBASE_DATABASE_SECRET/versions/latest
    env: 'FIREBASE_DATABASE_SECRET'
  - versionName: projects/combo-624e1/secrets/JWT_SECRET/versions/latest
    env: 'JWT_SECRET'
