name: Android CI/CD

on:
  push:
    branches: [ master ]
    tags:
      - 'v*' # Push events matching v1.0, v20.15.10, etc.
  pull_request:
    branches: [ master ]

env:
  PACKAGE_NAME: com.combo.app

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'mobile/package-lock.json'
    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ./mobile
      
{{ ... }}
      run: |
        ./gradlew assembleRelease
        
    # Upload APK as artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: mobile/app/build/outputs/apk/release/app-release.apk
        retention-days: 7
        
{{ ... }}
        file: mobile/app/build/outputs/apk/release/app-release.apk
        releaseNotes: "${{ github.event.head_commit.message }}"
    
    # Create GitHub Release for tags
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mobile/app/build/outputs/apk/release/app-release.apk
        generate_release_notes: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
