name: Android CI/CD

on:
  push:
    branches: [ master ]
    tags:
      - 'v*' # Push events matching v1.0, v20.15.10, etc.
  pull_request:
    branches: [ master ]

env:
  PACKAGE_NAME: com.combo.app

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'mobile/package-lock.json'

    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      working-directory: ./mobile
      
    # Set up keystore for signing
    - name: Set up keystore
      run: |
        mkdir -p android/app
        echo "${{ secrets.KEYSTORE }}" | base64 -d > android/app/upload-keystore.jks
      shell: bash
        
    # Build the app
    - name: Build APK
      working-directory: ./mobile
      run: |
        ./gradlew assembleRelease
        
    # Upload APK as artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: mobile/app/build/outputs/apk/release/app-release.apk
        retention-days: 7
        
    # Deploy to Firebase App Distribution
    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        file: mobile/app/build/outputs/apk/release/app-release.apk
        releaseNotes: "${{ github.event.head_commit.message }}"
    
    # Create GitHub Release for tags
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mobile/app/build/outputs/apk/release/app-release.apk
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
