name: Android CI/CD

on:
  push:
    branches: [ master ]
    tags:
      - 'v*' # Push events matching v1.0, v20.15.10, etc.
  pull_request:
    branches: [ master ]

env:
  PACKAGE_NAME: com.combo.app

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'mobile/package-lock.json'

    - name: Install dependencies
      working-directory: ./mobile
      run: npm ci

    # Build the app
    - name: Build APK
      working-directory: ./mobile
      run: |
        npm install -g @expo/eas-cli
        eas build --platform android --local
        
    # Upload APK as artifact
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: mobile/dist/*.apk
        retention-days: 7
        
    # Deploy to Firebase App Distribution
    - name: Upload to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
      with:
        appId: ${{ secrets.FIREBASE_APP_ID }}
        token: ${{ secrets.FIREBASE_TOKEN }}
        groups: testers
        file: mobile/dist/*.apk
        releaseNotes: "${{ github.event.head_commit.message }}"
    
    # Create GitHub Release for tags
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mobile/dist/*.apk
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
