name: Firebase Android Deploy

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # Release builds
  workflow_dispatch: # Manual trigger

env:
  FIREBASE_PROJECT_ID: combo-624e1
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    name: Build and Deploy to Firebase
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=service-account.json

    - name: Install dependencies
      run: |
        npm ci

    - name: Build web app for hosting
      run: |
        npm run build

    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --only hosting --project ${{ env.FIREBASE_PROJECT_ID }} --non-interactive

    - name: Build APK for Android
      run: |
        # Install EAS CLI
        npm install -g @expo/eas-cli
        
        # Login to Expo
        echo "${{ secrets.EXPO_ACCESS_TOKEN }}" | npx eas login --non-interactive
        
        # Build APK
        npx eas build --platform android --profile preview --non-interactive --output-path app-release.apk

    - name: Upload APK to Firebase App Distribution
      run: |
        firebase appdistribution:distribute app-release.apk \
          --app ${{ secrets.FIREBASE_APP_ID }} \
          --groups "testers" \
          --release-notes "Build from commit ${{ github.sha }}" \
          --project ${{ env.FIREBASE_PROJECT_ID }}

    - name: Deploy Firebase Functions and Rules
      run: |
        cd functions
        npm ci
        cd ..
        firebase deploy --only functions,firestore:rules,firestore:indexes,storage \
          --project ${{ env.FIREBASE_PROJECT_ID }} \
          --non-interactive

    - name: Comment deployment URL on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `???? Firebase deployment completed!\n\n???? **Web App**: https://${{ env.FIREBASE_PROJECT_ID }}.web.app\n???? **Android App**: Check Firebase App Distribution\n??? **API**: https://us-central1-${{ env.FIREBASE_PROJECT_ID }}.cloudfunctions.net/api\n\nCommit: ${{ github.sha }}`
          })

    - name: Notify on deployment failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `??? Firebase deployment failed. Check the workflow logs for details.`
          })
