#!/bin/bash

# EAS Build GitHub Secrets Setup Script
# This script helps you set up the required secrets for EAS Build in GitHub

echo "???? Setting up EAS Build secrets for GitHub Actions"
echo ""
echo "You need to set the following secrets in your GitHub repository:"
echo ""
echo "1. EXPO_ACCESS_TOKEN - Your Expo access token"
echo "   - Get it from: https://expo.dev/settings/access-tokens"
echo "   - Required for EAS authentication"
echo ""
echo "2. EXPO_ACCOUNT - Your Expo account username"
echo "   - Usually your Expo username"
echo ""
echo "3. EXPO_PROJECT - Your Expo project slug"
echo "   - Found in your app.json file"
echo ""
echo "4. FIREBASE_APP_ID (optional) - For Firebase App Distribution"
echo "   - Get from Firebase Console > Project Settings > General > Your apps"
echo ""
echo "5. FIREBASE_TOKEN (optional) - For Firebase App Distribution"
echo "   - Generate from Firebase CLI: firebase login:ci"
echo ""
echo "To set these secrets:"
echo "1. Go to your repository on GitHub"
echo "2. Navigate to Settings > Secrets and variables > Actions"
echo "3. Click 'New repository secret'"
echo "4. Add each secret with the name and value"
echo ""
echo "After setting up secrets, your EAS Build workflow will be ready!"
echo ""
echo "???? Learn more: https://docs.expo.dev/build/setup/"
