#!/bin/bash

# Firebase Deployment Secrets Setup Script - Focused Workflows
# This script helps you set up the required secrets for focused Firebase deployment workflows

echo "???? Firebase Deployment - Focused Workflows Setup"
echo "================================================="
echo ""
echo "???? FOCUSED WORKFLOWS CREATED:"
echo ""
echo "???? android-firebase-deploy.yml - Android APK ??? Firebase App Distribution"
echo "???? web-firebase-deploy.yml - Web App ??? Firebase Hosting"
echo ""
echo "???? REQUIRED SECRETS:"
echo ""

echo "1. FIREBASE_SERVICE_ACCOUNT - Firebase service account JSON key"
echo "   ???? Get from: Firebase Console > Project Settings > Service Accounts > Generate Private Key"
echo "   ???? Required for: Firebase CLI authentication"
echo ""
echo "2. FIREBASE_APP_ID - Your Firebase Android app ID"
echo "   ???? Get from: Firebase Console > Project Settings > General > Your apps > App ID"
echo "   ???? Required for: Firebase App Distribution (Android workflow only)"
echo ""
echo "3. FIREBASE_PROJECT_ID - Your Firebase project ID"
echo "   ???? Get from: Firebase Console > Project Settings > General > Project ID"
echo "   ???? Required for: Firebase project identification"
echo ""
echo "4. EXPO_ACCESS_TOKEN - Your Expo access token"
echo "   ???? Get from: https://expo.dev/settings/access-tokens"
echo "   ???? Required for: EAS CLI authentication (Android workflow only)"
echo ""

echo "???? SETUP INSTRUCTIONS:"
echo ""
echo "1. Go to your repository on GitHub"
echo "2. Navigate to: Settings > Secrets and variables > Actions"
echo "3. Click 'New repository secret'"
echo "4. Add each secret with the name and value from above"
echo ""
echo "???? FIREBASE SERVICE ACCOUNT SETUP:"
echo ""
echo "1. Go to Firebase Console: https://console.firebase.google.com"
echo "2. Select your project: combo-624e1"
echo "3. Go to: Project Settings > Service Accounts"
echo "4. Click 'Generate new private key'"
echo "5. Download the JSON file"
echo "6. Copy the entire JSON content"
echo "7. Paste as FIREBASE_SERVICE_ACCOUNT secret value"
echo ""
echo "???? FIREBASE APP ID SETUP:"
echo ""
echo "1. In Firebase Console, go to: Project Settings > General"
echo "2. Scroll to 'Your apps' section"
echo "3. Find your Android app and copy the App ID"
echo "4. Paste as FIREBASE_APP_ID secret value"
echo ""
echo "???? EAS BUILD SETUP:"
echo ""
echo "1. Go to: https://expo.dev/settings/access-tokens"
echo "2. Create new access token"
echo "3. Copy the token"
echo "4. Paste as EXPO_ACCESS_TOKEN secret value"
echo ""
echo "??? After setting up secrets:"
echo ""
echo "??? Android workflow will build APK and deploy to Firebase App Distribution"
echo "??? Web workflow will build and deploy to Firebase Hosting"
echo "??? Both workflows run automatically on pushes to main/master"
echo ""
echo "???? Your focused Firebase deployment is ready!"
