name: Web Firebase Hosting Deploy

on:
  push:
    branches: [ main, master ]
    paths:
      - 'mobile/**'
      - 'web/**'
      - 'frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  FIREBASE_PROJECT_ID: combo-624e1

jobs:
  build-and-deploy:
    name: Deploy Web App to Firebase Hosting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'

    - name: Install dependencies
      run: |
        npm ci

    - name: Prepare web build
      run: |
        # For now, use the static web build
        # In future, this can be replaced with proper React Native web build
        mkdir -p firebase-public

    - name: Copy web files
      run: |
        # Copy static web files to deployment directory
        cp -r web-build/* firebase-public/ 2>/dev/null || echo "Using static files"

    - name: Install Firebase CLI
      run: |
        npm install -g firebase-tools

    - name: Authenticate with Firebase
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json
        export GOOGLE_APPLICATION_CREDENTIALS=service-account.json

    - name: Deploy to Firebase Hosting
      run: |
        firebase deploy --only hosting --project ${{ env.FIREBASE_PROJECT_ID }} --non-interactive

    - name: Comment deployment URL
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `???? Web app deployed to Firebase Hosting!\n\n**URL:** https://${{ env.FIREBASE_PROJECT_ID }}.web.app\n**Commit:** ${{ github.sha }}\n**Build Time:** ${new Date().toISOString()}`
          })

    - name: Notify on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `??? Web app deployment failed. Check the workflow logs for details.`
          })
